name: Github Actions Task 1

on: push

jobs:
  hello-and-cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Hello World
        run: echo "Hello World from Youssef's Workflow 🎉"

      - name: Step 2 - Install cowsay and run it
        run: |
          sudo apt update -y
          sudo apt install cowsay -y
          cowsay "GitHub Actions is Fun!" > cow.txt
          cat cow.txt

  readme-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Step 3 - Read README.md
        run: |
          if [ -f README.md ]; then
            echo "📄 README.md contents:"
            cat README.md
          else
            echo "❌ README.md not found"
          fi
